# Generated by Django 4.2.2 on 2023-06-30 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatParaf',
            fields=[
                ('id_cat_paraf', models.AutoField(db_column='idCatParaf', primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CatProve',
            fields=[
                ('id_cat_prove', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_catprove', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_prov', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_compra', models.DateField()),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('id_cat_prove', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='store.catprove')),
            ],
        ),
        migrations.CreateModel(
            name='Parafernalia',
            fields=[
                ('idparaf', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagen', models.ImageField(null=True, upload_to='items')),
                ('id_cat_paraf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.catparaf')),
            ],
        ),
    ]
