# Generated by Django 4.2.1 on 2023-05-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parafernalia',
            name='id',
        ),
        migrations.AddField(
            model_name='parafernalia',
            name='idparaf',
            field=models.CharField(default=2, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
