# Generated by Django 4.2.2 on 2023-07-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parafernalia',
            name='idparaf',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
