# Generated by Django 4.2.1 on 2023-05-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_parafernalia_id_parafernalia_idparaf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parafernalia',
            name='imagen',
            field=models.ImageField(upload_to='img'),
        ),
    ]
