# Generated by Django 4.2.2 on 2023-06-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_parafernalia_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='cat_paraf',
            fields=[
                ('id_cat_paraf', models.AutoField(db_column='id_cat_paraf', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
    ]
