# Generated by Django 4.2.2 on 2023-06-19 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_cat_paraf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_paraf',
            name='id_cat_paraf',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parafernalia',
            name='tipo',
            field=models.ForeignKey(db_column='id_cat_paraf', on_delete=django.db.models.deletion.CASCADE, to='store.cat_paraf'),
        ),
    ]
