# Generated by Django 4.2.2 on 2023-06-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_cat_paraf_id_cat_paraf_alter_parafernalia_tipo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cat_paraf',
            new_name='CatParaf',
        ),
        migrations.RenameField(
            model_name='catparaf',
            old_name='nombre',
            new_name='nombre_tipo',
        ),
        migrations.RenameField(
            model_name='parafernalia',
            old_name='tipo',
            new_name='id_cat_paraf',
        ),
    ]
