# Generated by Django 4.2.2 on 2023-06-19 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_cat_paraf_catparaf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catparaf',
            name='id_cat_paraf',
            field=models.AutoField(db_column='idCatParaf', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parafernalia',
            name='id_cat_paraf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.catparaf'),
        ),
    ]
